import Head from 'next/head'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>toyama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*Sidebar */}
        <Sidebar />


        {/*feed */}
        {/*witgets */}
        {/*modal */}
      </main>


    </div>
  )
}
